site_name: My Docs

nav:
  - Home: index.md
  - Aulas:
    - Aula 1: aulas/aula1.md
    - Aula 2: aulas/aula2.md

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
    - toc.follow
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: pt-BR
  # favicom:
  # logo:
  palette:
    - scheme: default
      toggle:
        icon: material/globe-light
        name: Dark mode
      primary: grey
      accent: grey
    - scheme: slate
      toggle:
        icon: material/globe-light-outline
        name: Light mode
      primary: grey
      accent: purplue